import "./ResumeReview.scss";

import type { ResumeReview as ResumeReviewType } from "../../../features/ai/types";

import ScoreCard from "../ScoreCard/ScoreCard";
import InsightSection from "../InsightSection/InsightSection";
import { motion } from "framer-motion";
import { fadeUp, staggerContainer } from "../../../animation/fade";
import {
  strengthConfig,
  weaknessConfig,
  missingSkillsConfig,
} from "../../../constants/resume/insightSection";
import SummaryCard from "../Summary/Summary";

interface ResumeReviewProps {
  review: ResumeReviewType;
}

const ResumeReview = ({ review }: ResumeReviewProps) => {
  const insightSections = [
    {
      config: strengthConfig,
      items: review.strengths,
    },
    {
      config: weaknessConfig,
      items: review.weaknesses,
    },
    {
      config: missingSkillsConfig,
      items: review.missingSkills,
    },
  ];

  const topSections = insightSections.slice(0, 2);
  const bottomSection = insightSections[2];

  return (
    <section className="resume-review">
      <div className="resume-review__header">
        <h2>AI Resume Analysis</h2>

        <p>
          Here's a detailed analysis of your resume generated by HireCoder AI.
        </p>
      </div>

      <motion.div
        variants={staggerContainer}
        initial="hidden"
        animate="visible"
        className="resume-review__dashboard"
      >
        <motion.div variants={fadeUp}>
          {" "}
          <ScoreCard score={review.atsScore} />
        </motion.div>

        <div className="resume-review__grid">
          {topSections.map((section) => (
            <motion.div variants={fadeUp} key={section.config.title}>
              {" "}
              <InsightSection
                key={section.config.title}
                config={section.config}
                items={section.items}
              />
            </motion.div>
          ))}
        </div>

        <motion.div variants={fadeUp}>
          {" "}
          <InsightSection
            config={bottomSection.config}
            items={bottomSection.items}
          />
        </motion.div>
        <motion.div variants={fadeUp}>
          {" "}
          <SummaryCard summary={review.summary} />
        </motion.div>
      </motion.div>
    </section>
  );
};

export default ResumeReview;
