import "./ResumeReview.scss";

import type { ResumeReview as ResumeReviewType } from "../../../features/ai/types";

import { motion } from "framer-motion";

import ScoreCard from "../ScoreCard/ScoreCard";
import InsightSection from "../InsightSection/InsightSection";
import InterviewChance from "../InterviewChance/InterviewChance";
import SummaryCard from "../Summary/Summary";

import { fadeUp, staggerContainer } from "../../../animation/fade";

import {
  strengthConfig,
  weaknessConfig,
  missingSkillsConfig,
} from "../../../constants/resume/insightSection";

interface ResumeReviewProps {
  review: ResumeReviewType;
}

const ResumeReview = ({ review }: ResumeReviewProps) => {
  const insightSections = [
    {
      config: strengthConfig,
      items: review.strengths,
    },
    {
      config: weaknessConfig,
      items: review.weaknesses,
    },
    {
      config: missingSkillsConfig,
      items: review.missingSkills,
    },
  ];

  const topSections = insightSections.slice(0, 2);

  const bottomSection = insightSections[2];

  return (
    <section className="resume-review">
      {/* ======================================================
          Header
      ====================================================== */}

      <div className="resume-review__header">
        <h2>AI Resume Analysis</h2>

        <p>
          Here's a detailed analysis of your resume generated by HireCoder AI.
        </p>
      </div>

      <motion.div
        variants={staggerContainer}
        initial="hidden"
        animate="visible"
        className="resume-review__dashboard"
      >
        {/* ====================================================
            ATS Score + Interview Chance
        ==================================================== */}

        <div className="resume-review__overview">
          <motion.div variants={fadeUp}>
            <ScoreCard score={review.atsScore} />
          </motion.div>

          <motion.div variants={fadeUp}>
            <InterviewChance chance={review.interviewChance} />
          </motion.div>
        </div>

        {/* ====================================================
            Strengths + Weaknesses
        ==================================================== */}

        <div className="resume-review__grid">
          {topSections.map((section) => (
            <motion.div variants={fadeUp} key={section.config.title}>
              <InsightSection config={section.config} items={section.items} />
            </motion.div>
          ))}
        </div>

        {/* ====================================================
            Missing Skills
        ==================================================== */}

        <motion.div variants={fadeUp}>
          <InsightSection
            config={bottomSection.config}
            items={bottomSection.items}
          />
        </motion.div>

        {/* ====================================================
            Summary
        ==================================================== */}

        <motion.div variants={fadeUp}>
          <SummaryCard summary={review.summary} />
        </motion.div>
      </motion.div>
    </section>
  );
};

export default ResumeReview;
